-- Migration 013 — BATCH 2 of 3: Templates 1-10
-- Paste this into Supabase SQL Editor AFTER batch 1 completes

INSERT INTO toolbox_talk_templates (category, title, talking_points, hazards, ppe_required, duration_minutes, osha_reference, is_system) VALUES

('falls', 'Working at Heights — Fall Prevention', 
  ARRAY['Any work 6 feet or more above a lower level requires fall protection per OSHA standards. This includes edges, holes, and open sides.','Before starting elevated work, inspect your harness for frayed webbing, cracked D-rings, and proper stitching. A damaged harness is the same as no harness.','Anchor points must support 5,000 lbs per attached worker. Never tie off to conduit, handrails, or unsecured structures.','Guardrails must be 42 inches high (±3 inches) with a mid-rail at 21 inches. Check that all connections are tight before trusting them.','Cover all floor holes with material rated for twice the expected load. Mark covers clearly — write "HOLE" on them and secure so they cannot be displaced.','Self-retracting lifelines (SRLs) must be inspected before each use. Check the housing for cracks and test the brake by giving a sharp tug.','Report any missing or damaged fall protection immediately. If you see an unprotected edge, stop work and notify your foreman — do not walk past it.'],
  ARRAY['falls from elevation','unprotected edges','floor openings','inadequate anchorage'],
  ARRAY['full body harness','hard hat with chin strap','safety glasses','work boots'],
  15, '29 CFR 1926.501-503', true),

('ladders', 'Ladder Safety — Setup, Inspection & Use',
  ARRAY['Inspect every ladder before use: check rungs, side rails, spreaders, and feet. If anything is bent, cracked, or missing — tag it out and remove it from service.','Set extension ladders at a 4:1 ratio — for every 4 feet of height, the base should be 1 foot away from the wall. Extend 3 feet above the landing.','Maintain three points of contact at all times: two hands and one foot, or two feet and one hand. Never carry tools in your hands while climbing.','Never stand on the top two rungs of a stepladder or the top three rungs of an extension ladder. Use the right size ladder for the job.','Place ladders on firm, level surfaces. Never set a ladder on scaffolding, boxes, or unstable ground. Use leg levelers on uneven terrain.','Do not use metal ladders near electrical work or energized equipment. Use fiberglass ladders rated for electrical exposure.','Secure the top and bottom of extension ladders to prevent displacement. Have a spotter at the base when working in high-traffic areas.'],
  ARRAY['falls from ladders','ladder tip-over','electrical contact','overreaching'],
  ARRAY['hard hat','safety glasses','work boots','gloves'],
  10, '29 CFR 1926.1053', true),

('scaffolding', 'Scaffolding Safety — Erection, Use & Dismantling',
  ARRAY['Only competent persons may erect, modify, or dismantle scaffolding. If you are not trained, do not touch scaffold components.','Inspect scaffolding at the start of each shift and after any event that could affect integrity — storms, impacts, or extended idle periods.','All scaffold platforms must be fully planked with no gaps greater than 1 inch. Planks must extend 6 to 12 inches past supports.','Guardrails, mid-rails, and toeboards are required on all open sides when the platform is 10 feet or more above the ground.','Never exceed the scaffold load rating. Know the rated capacity and account for workers, tools, and materials combined.','Lock all caster wheels on mobile scaffolds before anyone climbs. Never move a mobile scaffold with workers on the platform.','Access scaffolds via built-in ladders, stair towers, or approved access points only — never climb cross-braces.'],
  ARRAY['scaffold collapse','falls from scaffold','falling objects','platform failure'],
  ARRAY['hard hat','safety glasses','work boots','harness when required'],
  15, '29 CFR 1926.451-454', true),

('electrical', 'Arc Flash & Electrical Shock Prevention',
  ARRAY['Assume all electrical circuits are energized until you personally verify they are de-energized using a rated voltage tester. Test the tester before and after use.','Only qualified electrical workers may perform work on or near energized circuits. If you are not qualified, maintain the approach boundary distance.','Wear arc-rated PPE appropriate to the incident energy level. Check the arc flash label on every panel before opening — it tells you the required PPE category.','Never use damaged or unrated tools near electrical equipment. All hand tools must be insulated and rated for the voltage present.','Keep all panel doors and covers closed and secured when not actively being worked on. Missing knockouts and open enclosures are an arc flash risk.','Know the location of the nearest emergency disconnect and how to use it. In an electrical emergency, de-energize first — do not touch the victim if they are still in contact with the source.'],
  ARRAY['arc flash','electrical shock','electrocution','burns'],
  ARRAY['arc-rated clothing','insulated gloves','face shield','safety glasses','voltage-rated tools'],
  15, '29 CFR 1926.405-408 / NFPA 70E', true),

('electrical', 'GFCI Protection & Temporary Power Safety',
  ARRAY['All 120-volt, 15 and 20 amp receptacles on construction sites must be GFCI-protected. No exceptions — this applies to extension cords, power strips, and temporary panels.','Test GFCIs before each use by pressing the TEST button. The RESET button should pop out. If it does not trip, the GFCI is defective — remove it from service.','Inspect all extension cords daily: look for exposed conductors, damaged insulation, missing ground prongs, and proper strain relief. Damaged cords get cut and trashed — do not tape them.','Route temporary power cords to avoid damage from traffic, sharp edges, and pinch points. Cords cannot run through doorways, windows, or holes unless protected from damage.','Temporary lighting must be protected by guards unless the bulbs are deeply recessed. Broken lamps in wet areas are a shock hazard.','Never daisy-chain power strips or use indoor-rated cords outdoors. Match the cord to the environment and the load.'],
  ARRAY['electrical shock','electrocution','damaged cords','ground faults'],
  ARRAY['safety glasses','insulated gloves when testing','work boots'],
  10, '29 CFR 1926.404-405', true),

('struck_by', 'Struck-By Hazards — Overhead Protection',
  ARRAY['Hard hats are mandatory in all areas where there is a risk of falling objects, overhead work, or low clearance. Wear them properly — not backwards unless designed for it.','Never work directly below overhead operations without barriers or a controlled access zone. If a crew is working above, no one should be standing underneath without protection.','Secure all tools and materials at height with lanyards, toe boards, or debris nets. A 2-pound wrench dropped from 6 stories hits with over 200 pounds of force.','Barricade areas below crane operations, overhead lifts, and leading-edge work. Use flagging tape, cones, and signage to define the drop zone.','Inspect hard hats daily for cracks, dents, and UV degradation. Replace the suspension liner if it is stretched out or damaged. Replace the shell per manufacturer guidelines.','During demolition, establish exclusion zones around the work area. Debris can travel much farther than expected — especially in wind.'],
  ARRAY['falling tools','falling materials','overhead crane loads','demolition debris'],
  ARRAY['hard hat','safety glasses','high-visibility vest','steel-toe boots'],
  10, '29 CFR 1926.250-252', true),

('struck_by', 'Heavy Equipment Blind Spots & Pedestrian Safety',
  ARRAY['Heavy equipment operators have significant blind spots on all sides. If you cannot see the operator''s mirrors, the operator cannot see you. Stay in the operator''s line of sight.','Establish designated pedestrian walkways and equipment travel paths on site. Foot traffic and heavy equipment should never share the same lane without barriers.','Spotters are required when equipment is backing up or operating in congested areas. Use radios and maintain visual contact with the operator at all times.','High-visibility vests are required in all equipment operating areas. Class 2 minimum during the day, Class 3 at night or in low-visibility conditions.','Never approach heavy equipment until the operator has acknowledged your presence and the machine is stationary. Make eye contact or use a radio — do not assume they see you.','Dump trucks, excavators, and loaders should have functioning backup alarms. If the alarm is not working, shut the equipment down until it is repaired.','During fueling, shut off the engine and do not smoke within 50 feet. Keep a fire extinguisher readily accessible at all fueling locations.'],
  ARRAY['struck by equipment','backing accidents','crushed by vehicle','pedestrian contact'],
  ARRAY['high-visibility vest','hard hat','safety glasses','steel-toe boots'],
  15, '29 CFR 1926.600-602', true),

('excavation', 'Trenching & Excavation Safety',
  ARRAY['All excavations 5 feet or deeper require a protective system: sloping, benching, shoring, or a trench box. There are no exceptions — even for "just a few minutes."','A competent person must inspect the excavation daily, after every rainstorm, and after any event that could affect conditions. Document every inspection.','Never enter a trench that does not have a safe means of egress within 25 feet of travel. Ladders must extend 3 feet above the top of the trench.','Keep all spoil piles, materials, and equipment at least 2 feet from the edge of the excavation. Surcharge loading is the leading cause of trench wall failure.','Know the location of all underground utilities before digging. Call 811 at least 48 hours before excavation. Hand-dig within the tolerance zone of marked utilities.','Watch for signs of distress: tension cracks in the soil, bulging at the base, water seepage, or previously backfilled ground. If you see any of these, evacuate immediately.','Atmospheric testing is required in excavations deeper than 4 feet where hazardous atmospheres could exist — near landfills, fuel tanks, or gas lines.'],
  ARRAY['cave-in','engulfment','atmospheric hazards','falling into excavation','utility strikes'],
  ARRAY['hard hat','high-visibility vest','work boots','gas monitor when required'],
  15, '29 CFR 1926.650-652', true),

('caught_between', 'Caught In/Between — Machine Guarding & Pinch Points',
  ARRAY['Never remove, bypass, or disable machine guards. Guards exist because someone was injured or killed at that exact point. Treat them as non-negotiable.','Identify all pinch points, nip points, and rotating parts before starting work near machinery. If your hands or clothing could get pulled in, add a guard or stay clear.','Loose clothing, jewelry, long hair, and lanyards near rotating equipment are catch hazards. Secure everything before operating or working near moving parts.','Before performing maintenance on any equipment, follow Lockout/Tagout procedures. "I''ll just be a second" has been the last thing too many people said.','Inspect all guards and safety devices at the start of each shift. If a guard is damaged or missing, tag the machine out and notify your supervisor immediately.','Keep hands and fingers clear of shear points on hydraulic tools, metal brakes, and presses. Use push sticks, jigs, or remote controls when available.'],
  ARRAY['caught in machinery','pinch points','rotating parts','crushing','amputation'],
  ARRAY['safety glasses','close-fitting clothing','work gloves when appropriate','hearing protection'],
  10, '29 CFR 1926.300-307', true),

('confined_space', 'Confined Space Entry — Permit & Non-Permit',
  ARRAY['A confined space has limited entry/exit, is not designed for continuous occupancy, and is large enough to bodily enter. Manholes, tanks, vaults, and pits all qualify.','Before entry, test the atmosphere for oxygen (19.5-23.5%), combustible gas (<10% LEL), and toxic gases (H₂S <10ppm, CO <35ppm). Test at multiple levels — gases stratify.','A completed entry permit must be posted at the opening before anyone enters. The permit lists hazards, controls, rescue provisions, and authorized entrants.','An attendant must be stationed at the opening at all times during entry. The attendant''s only job is to monitor entrants and summon rescue — they do not enter the space.','Continuous ventilation with a mechanical blower is required to maintain safe atmospheric conditions. Position the duct to reach the work area at the bottom of the space.','Have a rescue plan before entry. Non-entry rescue (retrieval systems with tripod and winch) is preferred. If the plan relies on the fire department, confirm their response time.','If atmospheric conditions change or an entrant feels lightheaded, nauseated, or disoriented — evacuate immediately. Do not re-enter to rescue without proper equipment and training.'],
  ARRAY['oxygen deficiency','toxic atmosphere','engulfment','entrapment','combustible atmosphere'],
  ARRAY['gas monitor (4-gas)','full body harness','retrieval line','hard hat','safety glasses'],
  20, '29 CFR 1926.1200-1213', true);
