-- Migration 013 — BATCH 3 of 3: Templates 11-20
-- Paste this into Supabase SQL Editor AFTER batch 2 completes

INSERT INTO toolbox_talk_templates (category, title, talking_points, hazards, ppe_required, duration_minutes, osha_reference, is_system) VALUES

('ppe', 'PPE Selection, Inspection & Proper Use',
  ARRAY['PPE is the last line of defense — not the first. Always look for ways to eliminate or control the hazard before relying on personal protective equipment.','Hard hats: inspect the shell for cracks and the suspension for elasticity. Replace after any impact, even if damage is not visible. UV-degraded shells get chalky — replace them.','Safety glasses must meet ANSI Z87.1 — look for the marking on the lens and frame. Use side shields in all construction environments. Prescription glasses are not safety glasses unless rated.','Hearing protection is required when noise exceeds 85 dBA (8-hour TWA). If you have to raise your voice to talk to someone 3 feet away, you need hearing protection.','Gloves must match the hazard: cut-resistant for sharp materials, chemical-resistant for solvents, insulated for electrical work. The wrong glove is worse than no glove — it creates false confidence.','High-visibility vests are required wherever vehicle or equipment traffic is present. Class 2 minimum for daytime, Class 3 for nighttime or highway-adjacent work.','Respiratory protection requires medical clearance, fit testing, and training before use. A dust mask is not a respirator — know the difference and use the right protection for the exposure.'],
  ARRAY['head injury','eye injury','hearing loss','hand injury','respiratory exposure'],
  ARRAY['hard hat','safety glasses','hearing protection','work gloves','high-visibility vest','steel-toe boots'],
  15, '29 CFR 1926.95-107', true),

('heat_illness', 'Heat Illness Prevention — Water, Rest, Shade',
  ARRAY['Heat illness kills construction workers every year. The three defenses are simple: water, rest, and shade. Every crew must have all three available when temperatures exceed 80°F.','Drink water before you feel thirsty — by the time you are thirsty, you are already dehydrated. Target one cup (8 oz) every 15-20 minutes. Avoid energy drinks and excessive caffeine.','Know the signs of heat exhaustion: heavy sweating, weakness, cold/clammy skin, nausea, dizziness, fast/weak pulse. Move the person to shade, cool them down, and call for help.','Heat stroke is a medical emergency: high body temperature (>103°F), hot/red/dry skin, rapid pulse, confusion, loss of consciousness. Call 911 immediately and cool aggressively with water/ice.','New and returning workers need an acclimatization period. Start with 20% of normal workload on day one and increase 20% each day over the first week.','Schedule heavy work for early morning when possible. Rotate crews through shade breaks. Monitor each other — a buddy system catches heat illness early.','Ensure shade structures are set up before work begins. If natural shade is not available, pop-up canopies or tarps must be provided within a reasonable distance of the work area.'],
  ARRAY['heat exhaustion','heat stroke','dehydration','heat cramps','rhabdomyolysis'],
  ARRAY['light-colored clothing','wide-brim hard hat','cooling towels','sunscreen'],
  15, '29 CFR 1926.960 / OSHA Heat NEP', true),

('cold_stress', 'Cold Stress — Hypothermia, Frostbite & Prevention',
  ARRAY['Cold stress occurs when the body cannot maintain its core temperature. Wind chill is the real danger — a 35°F day with 25 mph wind feels like 23°F on exposed skin.','Dress in layers: a moisture-wicking base layer, an insulating middle layer, and a wind/water-resistant outer layer. Avoid cotton next to skin — it holds moisture and accelerates heat loss.','Know the signs of hypothermia: uncontrollable shivering, slurred speech, confusion, drowsiness, loss of coordination. This is a medical emergency — call 911 and warm the person gradually.','Frostbite affects fingers, toes, ears, and the nose first. Watch for numbness, tingling, or skin that appears waxy, white, or grayish-yellow. Do not rub frostbitten skin.','Take frequent warming breaks in a heated area. Have warm, sweet beverages available — avoid alcohol and caffeine, which impair the body''s ability to regulate temperature.','Schedule outdoor work during the warmest part of the day when possible. Increase rest periods as temperatures drop and wind increases.'],
  ARRAY['hypothermia','frostbite','trench foot','impaired dexterity','slips on ice'],
  ARRAY['insulated work gloves','thermal hard hat liner','insulated boots','layered clothing'],
  10, '29 CFR 1926.960 / OSHA Cold Stress Guide', true),

('fire_prevention', 'Fire Prevention & Hot Work Permits',
  ARRAY['A hot work permit is required for any cutting, welding, brazing, or grinding operation. The permit must be completed before work begins and posted at the work location.','Clear all combustible materials within 35 feet of hot work. If combustibles cannot be moved, cover them with fire-resistant blankets or welding curtains.','A fire watch must remain at the hot work location for at least 30 minutes after work is completed. The fire watch must have a charged fire extinguisher within reach.','Know the location and type of fire extinguishers on your project. A 10-lb ABC extinguisher must be within 100 feet of all hot work. Confirm the gauge shows a full charge.','Keep all compressed gas cylinders upright, capped when not in use, and secured with chains. Separate oxygen and fuel gas cylinders by 20 feet or a 5-foot fire-rated barrier.','Report any smell of gas, propane, or unusual odors immediately. Evacuate the area before investigating. Never use an open flame to check for gas leaks.','Maintain clear access to fire exits, extinguishers, and alarm pull stations at all times. Storage, materials, and equipment must not block egress paths.'],
  ARRAY['fire','explosion','burns','smoke inhalation','compressed gas hazards'],
  ARRAY['welding helmet','fire-resistant clothing','welding gloves','safety glasses with side shields'],
  15, '29 CFR 1926.352-354', true),

('hazcom', 'Hazard Communication — GHS Labels & SDS',
  ARRAY['Every chemical on site must have a Safety Data Sheet (SDS) accessible to all workers. Know where the SDS binder is located on your project — ask if you do not know.','GHS labels have six key elements: product name, signal word (Danger or Warning), hazard statements, precautionary statements, pictograms, and supplier information. Never use a chemical with a missing or illegible label.','If you transfer a chemical to a secondary container, that container must be labeled with the product name and the applicable hazards. No unmarked containers — ever.','The nine GHS pictograms tell you the hazard type at a glance: flame, oxidizer, compressed gas, corrosion, skull and crossbones, exclamation mark, health hazard, environment, exploding bomb. Learn them.','Before using any chemical you haven''t used before, read the SDS. Section 2 (hazards), Section 4 (first aid), and Section 8 (exposure controls/PPE) are the most critical sections.','Incompatible chemicals must be stored separately. Acids and bases, oxidizers and flammables — mixing them (even from spills) can cause fires, explosions, or toxic gas release.'],
  ARRAY['chemical exposure','inhalation','skin contact','chemical burn','toxic reaction'],
  ARRAY['chemical-resistant gloves','safety glasses or goggles','respirator when required','face shield for splash risk'],
  10, '29 CFR 1926.59 / 29 CFR 1910.1200', true),

('lockout_tagout', 'Lockout/Tagout — Energy Isolation for Maintenance',
  ARRAY['Lockout/Tagout applies to ANY energy source: electrical, pneumatic, hydraulic, mechanical, thermal, chemical, and gravity. If it can move, flow, or release, it must be isolated.','Only trained, authorized employees may perform lockout/tagout. Each person working on the equipment must apply their own lock and tag — no sharing locks.','The six steps of LOTO: (1) Notify affected employees, (2) Shut down equipment using normal procedures, (3) Isolate all energy sources, (4) Apply locks and tags, (5) Release stored energy, (6) Verify zero energy state.','After locking out, attempt to start the equipment to verify it is de-energized. Also test for residual voltage, pressure, or stored mechanical energy. Verify, then work.','Tags are information devices, not energy-isolating devices. A tag without a lock is insufficient unless a lock physically cannot be applied — and that exception must be documented.','Before removing your lock, inspect the work area, ensure all tools are removed, confirm all guards are replaced, and account for all workers. The last lock off means the equipment is live.','Never remove another person''s lock. If a worker leaves without removing their lock, only the site supervisor can authorize removal after verifying the worker has left and the equipment is clear.'],
  ARRAY['unexpected energization','electrocution','crushing','amputation','burns'],
  ARRAY['personal lockout padlock','lockout hasp','tags','voltage tester'],
  15, '29 CFR 1926.417 / 29 CFR 1910.147', true),

('crane_rigging', 'Crane & Rigging Safety — Lifts, Signals & Inspections',
  ARRAY['Only qualified riggers may rig loads and only qualified signal persons may direct crane operations. These designations require documented training — do not self-appoint.','Before every lift, create a lift plan: load weight, rigging configuration, crane capacity at radius, ground conditions, overhead obstructions, and wind speed limits. Critical lifts (>75% capacity) require an engineered lift plan.','Inspect all slings, shackles, and rigging hardware before use. Remove from service: frayed wire rope, stretched chain links, cut synthetic slings, or any hardware with visible damage.','Maintain a minimum clearance of 20 feet from power lines for all crane operations, or the voltage-specific distance in Table A of 29 CFR 1926.1408, whichever is greater.','Never walk under a suspended load. Establish a barricaded drop zone around every lift. If you must travel through the area, wait until the load is placed and the rigging is slack.','Use tag lines to control load rotation and swing. Never wrap a tag line around your hand or body — if the load moves unexpectedly, you need to be able to let go instantly.','Outriggers must be fully extended and set on adequate blocking before any lift. Never rely on tires for stability — the crane''s capacity chart assumes outriggers are properly deployed.'],
  ARRAY['dropped load','crane tip-over','power line contact','struck by load','rigging failure'],
  ARRAY['hard hat','safety glasses','high-visibility vest','work gloves','steel-toe boots'],
  20, '29 CFR 1926.1400-1442', true),

('silica', 'Silica Dust Exposure — Control & Prevention',
  ARRAY['Crystalline silica is found in concrete, brick, block, mortar, granite, and sand. Cutting, drilling, grinding, or demolishing these materials generates respirable silica dust that causes silicosis — a permanent, incurable lung disease.','OSHA''s permissible exposure limit (PEL) for respirable crystalline silica is 50 µg/m³ as an 8-hour TWA. Many common tasks exceed this limit without controls.','Use Table 1 controls when available: wet cutting with continuous water, vacuum dust collection systems, or enclosed cabs with HEPA filtration. These are your first-line defenses.','When engineering controls are not feasible, respiratory protection is required. A minimum of an N95 is needed for short-duration work; a half-face respirator with P100 filters for sustained exposure.','Never dry-sweep silica dust. Use HEPA vacuums or wet methods to clean up. Compressed air blow-down of silica dust is prohibited — it creates a hazardous cloud.','Workers exposed above the action level (25 µg/m³) must be enrolled in a medical surveillance program including chest X-ray and lung function testing every 3 years.'],
  ARRAY['silicosis','lung cancer','COPD','kidney disease','respirable dust exposure'],
  ARRAY['N95 or P100 respirator','safety glasses or goggles','disposable coveralls when warranted'],
  10, '29 CFR 1926.1153', true),

('hand_power_tools', 'Hand & Power Tool Safety — Inspection & Proper Use',
  ARRAY['Inspect all tools before use: check for cracked handles, mushroomed heads, frayed cords, damaged guards, and loose parts. Defective tools must be removed from service immediately.','Never remove or bypass a guard on a power tool. Guards exist because that tool has injured someone in exactly that way. If the guard interferes with the work, get the right tool.','Use the right tool for the job — the correct size, type, and rated capacity. Using a tool beyond its design (prying with a wrench, hammering with pliers) causes injuries and breaks tools.','Wear eye protection when using any striking tool, cutting tool, or power tool. Impact-rated safety glasses (ANSI Z87+) are required for tasks that generate flying particles.','Pneumatic tools must have safety clips or retainers to prevent attachments from being ejected. Never point a pneumatic nailer at anyone, even if you believe it is empty.','When using grinders, ensure the RPM rating of the wheel matches or exceeds the grinder''s RPM. An over-speed disc can shatter and send fragments like shrapnel.','Disconnect power tools from their power source before changing blades, bits, or accessories. For corded tools, unplug. For pneumatic, disconnect the air line. For battery, remove the battery.'],
  ARRAY['lacerations','eye injury','hand/finger amputation','flying debris','electrical shock'],
  ARRAY['safety glasses','work gloves','hearing protection for loud tools','face shield for grinding'],
  10, '29 CFR 1926.300-307', true),

('housekeeping', 'Housekeeping — Slip, Trip & Fall Prevention',
  ARRAY['Good housekeeping is not optional — it is an OSHA requirement and the single most effective way to prevent slips, trips, and falls on a construction site.','Clean as you go. Do not wait until the end of the shift to pick up debris, coil cords, and stack materials. A cluttered work area is an injury waiting to happen.','All walkways, stairways, and access paths must be kept clear of tools, cords, debris, and standing water. If it is in the path, move it or mark it.','Stack materials neatly and securely. Leaning stacks, unsecured pipe, and loose lumber are struck-by and trip hazards. Use dunnage to keep materials off the ground and organized.','Manage cords and hoses: run them overhead when possible, use cord covers at crossings, and coil excess. A cord across a walkway is a guaranteed trip within the hour.','Report and clean up spills immediately — water, oil, mud, concrete slurry. On smooth surfaces, apply absorbent material. Mark wet areas until they are dry.','Maintain proper lighting in all work and travel areas. Temporary lighting is required in stairwells, corridors, and interior spaces. If you cannot see the hazard, you cannot avoid it.'],
  ARRAY['slips','trips','falls on same level','struck by falling materials','fire from debris accumulation'],
  ARRAY['hard hat','safety glasses','work boots with tread','high-visibility vest'],
  10, '29 CFR 1926.25', true);
